// app/fetch-fonts.mjs — self-host Google Fonts at BUILD TIME so the running app makes ZERO
// font CDN requests. (619 — "make the web app 100% CDN-free")
//
// Why a build step (and not just committed files): the woff2 binaries can't be produced by hand.
// This script — run on a real machine during `npm run build:app` — asks the Google CSS2 endpoint
// (with a modern browser UA so it returns woff2, not legacy ttf), downloads every referenced
// woff2 into app/fonts/, rewrites the @font-face src URLs to LOCAL relative paths, and writes
// app/fonts.css. index.html links that local fonts.css instead of fonts.googleapis.com.
//
// Idempotent + offline-safe AFTER the first run: if app/fonts.css already exists and every file it
// references is present in app/fonts/, it skips the network entirely. So once fonts.css + the
// woff2 are committed (like leaflet.css), every later build — including offline ones — is a no-op.
// Only the FIRST build (or `npm run fonts:refresh`, which deletes fonts.css) needs network.
//
// Keep FAMILIES_URL in sync with the <link> spec that used to be in index.html.

import { mkdir, writeFile, readFile, stat, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here     = path.dirname(fileURLToPath(import.meta.url));
const fontsDir = path.join(here, 'fonts');
const cssOut   = path.join(here, 'fonts.css');

// Same two families / weights the app used from Google Fonts.
const FAMILIES_URL =
  'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700;800;900&family=Barlow:wght@400;500;600&display=swap';

// A modern-browser UA so CSS2 serves woff2 (the smallest, widely-supported format) and the full
// unicode-range subsets, rather than a single legacy ttf.
const MODERN_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15';

async function exists(p) { try { await stat(p); return true; } catch { return false; } }

// Already self-hosted? (fonts.css present and every referenced local file on disk) → skip network.
async function alreadyDone() {
  if (!(await exists(cssOut))) return false;
  const css = await readFile(cssOut, 'utf8');
  const refs = [...css.matchAll(/url\(\s*(?:'|")?(fonts\/[^)'"]+)(?:'|")?\s*\)/g)].map(m => m[1]);
  if (refs.length === 0) return false;
  for (const r of refs) if (!(await exists(path.join(here, r)))) return false;
  return true;
}

async function main() {
  if (await alreadyDone()) {
    console.log('✓ fonts already self-hosted (app/fonts.css + app/fonts/*) — skipping fetch');
    return;
  }

  console.log('• self-hosting Google Fonts (one-time build-time fetch)…');
  const res = await fetch(FAMILIES_URL, { headers: { 'User-Agent': MODERN_UA } });
  if (!res.ok) throw new Error(`fonts CSS fetch failed: HTTP ${res.status}`);
  let css = await res.text();

  // Collect every remote font URL (gstatic woff2) in the returned CSS.
  const urls = [...css.matchAll(/url\(\s*(https?:\/\/[^)]+?)\s*\)/g)].map(m => m[1]);
  if (urls.length === 0) throw new Error('no font URLs found in CSS — UA/endpoint may have changed');

  await mkdir(fontsDir, { recursive: true });

  // Download each unique URL → app/fonts/<basename>, and map remote→local for the rewrite.
  const map = new Map();
  for (const url of [...new Set(urls)]) {
    const base = path.basename(new URL(url).pathname);     // hashed, unique per subset/weight
    const dest = path.join(fontsDir, base);
    if (!(await exists(dest))) {
      const fr = await fetch(url, { headers: { 'User-Agent': MODERN_UA } });
      if (!fr.ok) throw new Error(`font download failed (${url}): HTTP ${fr.status}`);
      const buf = Buffer.from(await fr.arrayBuffer());
      await writeFile(dest, buf);
    }
    map.set(url, `fonts/${base}`);
  }

  // Rewrite every absolute URL to its local relative path.
  for (const [remote, local] of map) css = css.split(remote).join(local);

  const banner =
    '/* app/fonts.css — GENERATED by app/fetch-fonts.mjs. Self-hosted Barlow + Barlow Condensed\n' +
    '   so the app makes ZERO font CDN requests at runtime. Do not edit by hand; re-run\n' +
    '   `npm run build:app` (or `npm run fonts:refresh`) to regenerate. Commit this + app/fonts/. */\n\n';
  await writeFile(cssOut, banner + css.trim() + '\n');

  const files = await readdir(fontsDir);
  console.log(`✓ self-hosted ${files.length} font file(s) → app/fonts/, wrote app/fonts.css`);
}

main().catch((e) => { console.error('✗ fetch-fonts:', e.message); process.exit(1); });
