//  MainActivity.java
//  TEAM 3332 — Android entry point. (619d)
//
//  Capacitor 6 auto-discovers plugins shipped as npm packages, but HAND-WRITTEN local plugins
//  (LiveActivityPlugin.kt) must be registered explicitly here — the Android analog of iOS's
//  capacitor.config.json `packageClassList`. Without this registerPlugin() call the JS
//  registerPlugin('LiveActivity') proxy resolves to nothing and the run notification never shows
//  (no error, no log — same silent-failure shape as the iOS packageClassList gotcha).
//
//  `android/` is gitignored (regenerated by `npx cap add android`), so this committed copy lives in
//  android-native-src/. When you generate the project, replace the generated
//  android/app/src/main/java/com/team3332/app/MainActivity.java with this file (or just add the
//  registerPlugin line to the generated one). Re-do it if you ever re-run `cap add android`.

package com.team3332.app;

import android.os.Bundle;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        // Must be called BEFORE super.onCreate so the bridge picks the plugin up at init.
        registerPlugin(LiveActivityPlugin.class);
        super.onCreate(savedInstanceState);
    }
}
